site_name: Snowflake Account Evaluator dbt package
site_url: https://gitlab.infinitelambda.com/snowflake-evaluator
site_author: Infinite Lambda
site_description: Offical documentation of `diqu` CLI

repo_name: infinitelambda/snowflake-evaluator
repo_url: https://gitlab.infinitelambda.com/infinitelambda/bi-chapter/snowflake-evaluator
edit_uri: edit/main/docs/

copyright: Copyright &copy; 2023 Infinite Lambda

nav:
  - What is it?:
    - What is it?: index.md
    - ...


theme:
  name: material
  # custom_dir: docs/overrides
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  palette:
    - media: "(prefers-color-scheme)"
      primary: black
      scheme: slate
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      primary: black
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: black
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.ico
  logo: assets/favicon.ico
  icon:
    repo: fontawesome/brands/github

plugins:
    - search
    - awesome-pages